GET  http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJFbmNlcCBTdXJ5YW5hIiwiZW1haWwiOiJlbmNlcEBnbWFpbC5jb20iLCJpYXQiOjE2NDE4OTU0NzUsImV4cCI6MTY0MTg5NTQ5MH0.lJeSJdogegAVWF2zSD-4mZYJryEodx_9pizg-B6fgPU

###
POST  http://localhost:5000/users
Content-Type: application/json

{
    "name": "Encep Suryana",
    "email": "encep2@gmail.com",
    "password": "123456",
    "confPassword": "123456"
}

###
POST  http://localhost:5000/login
Content-Type: application/json

{
    "email": "encep@gmail.com",
    "password": "123456"
}

###
GET  http://localhost:5000/token


###
DELETE   http://localhost:5000/logout
